export const SET_RIGHT_ANSWER = 'SET_RIGHT_ANSWER';
export const CHANGE_IS_FORM_VALID = 'CHANGE_IS_FORM_VALID';
export const CHANGE_FORM_CONTROLS = 'CHANGE_FORM_CONTROLS';
export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION';
